name: FF
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip:
    - torch==1.7.1
    - torchvision==0.8.2
    - mmcv==2.0.1
    - mmengine==0.10.4
    - mmselfsup==1.0.0
    - pyqt5==5.15.11
