 name: FF
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - torchvision
  - pip
  - pip:
      - mmcv==2.0.1
      - mmengine==0.10.4
      - mmselfsup==1.0.0
      - pyqt5==5.15.11